"""chat limit chaking table added

Revision ID: a7df6456925f
Revises: a016be0e0d03
Create Date: 2025-07-27 17:08:28.925821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7df6456925f'
down_revision: Union[str, Sequence[str], None] = 'a016be0e0d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_message_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('usage_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='unique_user_daily_usage')
    )
    op.create_table('user_total_time',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.uid'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_table('user_total_time')
    op.drop_table('user_daily_message_usage')
    # ### end Alembic commands ###
